In [1]:
import csv
import re
import tensorflow as tf
%matplotlib inline
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
def readCSV(csv_path, skip_firstRow=False, separator=',', encoding="utf-8-sig"):
    data = []
    with open(csv_path, 'rt', encoding=encoding) as csvfile:
        csvreader = csv.reader(csvfile, delimiter=separator)
        for row in csvreader:
            if not skip_firstRow:
                data.append(row)
            skip_firstRow = False
    return data

In [3]:
list_one = readCSV('lungcheck_200813_drink.csv',skip_firstRow=True)

In [4]:
list_one[:10]

[['27357648',
  '20170214',
  '79',
  '-',
  '',
  '맥주',
  '1',
  '79',
  '',
  '0.5',
  '',
  '1',
  '',
  '4'],
 ['27377046',
  '20170307',
  '75',
  '10년간',
  '10',
  '소주',
  '2',
  '65',
  '65',
  '3-5잔',
  '',
  '2회/주',
  '8',
  '1'],
 ['27392425',
  '20170226',
  '67',
  '40년',
  '40',
  '막걸리,맥주,소주',
  '1,2,4',
  '27',
  '27',
  '3-5잔',
  '',
  '2',
  '',
  '2'],
 ['27392425',
  '20180318',
  '68',
  '40년',
  '40',
  '',
  '',
  '28',
  '28',
  '3-5잔',
  '',
  '주 2회 ',
  '8',
  '3'],
 ['27393101',
  '20180703',
  '44',
  '20년',
  '20',
  '',
  '',
  '24',
  '24',
  '2병',
  '2',
  '2회',
  '',
  '3'],
 ['27396737',
  '20170301',
  '52',
  '10년간 ',
  '10',
  '소주',
  '2',
  '42',
  '42',
  '3~5잔/일 ',
  '',
  '1회/주 ',
  '4',
  '1'],
 ['27404892',
  '20170628',
  '44',
  '25년',
  '25',
  '맥주',
  '1',
  '19',
  '19',
  '6~10잔',
  '',
  '2/주',
  '8',
  '1'],
 ['27404892',
  '20170711',
  '44',
  '25',
  '25',
  '맥주',
  '1',
  '19',
  '19',
  '06월 10일',
  '',
  '2',
  '',
  '2'],
 ['27425

In [5]:
x=[]
xmax=0
for i in list_one:
    x.append(i[11])
    xmax=max(xmax,len(i[11]))
xmax

19

In [6]:
y=[]
ymax=0
for i in list_one:
    try:
        y.append(float(i[12]))
        ymax=max(ymax,float(i[12]))
    except:
        y.append(0)
ymax=int(ymax)
ymax

40

In [7]:
def setencetochar(sentences):
    charpaddedsentence=[]
    for sentence in sentences:
        charpaddedsentence.append([sentence.ljust(xmax,'#')])
    return charpaddedsentence

In [8]:
x=setencetochar(x)

In [9]:
x[:10]

[['1##################'],
 ['2회/주###############'],
 ['2##################'],
 ['주 2회 ##############'],
 ['2회#################'],
 ['1회/주 ##############'],
 ['2/주################'],
 ['2##################'],
 ['1주일/1회#############'],
 ['1주일/1회#############']]

In [10]:
def separateChar(Sentences):
    total=[]
    for i, sentence in enumerate(Sentences):
        Sen=[]
        for j, chars in enumerate(sentence):
            Sen.extend(chars)
        total.append(Sen)
    return total

In [11]:
x_testing = separateChar(x)

In [12]:
src_tokenizer = Tokenizer()
src_tokenizer.fit_on_texts(x_testing)

In [13]:
input_dim= len(src_tokenizer.word_index) + 1
input_dim

132

In [14]:
x_train_real, x_test_real, y_train, y_test = train_test_split(x_testing, y, test_size=0.3, shuffle=False, random_state=1004)

In [15]:
len(y_train)

3594

In [16]:
x_train=src_tokenizer.texts_to_sequences(x_train_real)
x_test=src_tokenizer.texts_to_sequences(x_test_real)

In [17]:
x_train_real[:20]

[['1',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['2',
  '회',
  '/',
  '주',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['2',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['주',
  ' ',
  '2',
  '회',
  ' ',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['2',
  '회',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['1',
  '회',
  '/',
  '주',
  ' ',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['2',
  '/',
  '주',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#'],
 ['2',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',
  '#',

In [18]:
x_train[:20]

[[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [6, 3, 4, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [5, 8, 6, 3, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [6, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 3, 4, 5, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [6, 4, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 5, 7, 4, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 5, 7, 4, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [20, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [20, 4, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [15, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 11, 6, 3, 4, 5, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 11, 6, 3, 4, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 11, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [18, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [19]:
for i in x_train:
    xmax_2=max(xmax,len(i))
xmax_2

19

In [20]:
index_to_word = src_tokenizer.index_word

In [21]:
x_train = pad_sequences(x_train, padding='post', maxlen=xmax_2)
x_test = pad_sequences(x_test, padding='post', maxlen=xmax_2)

In [22]:
y_train = to_categorical(y_train,num_classes=ymax+1)
y_test = to_categorical(y_test,num_classes=ymax+1)

In [23]:
x_train.shape

(3594, 19)

In [24]:
x_train[:20]

array([[ 2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 6,  3,  4,  5,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 5,  8,  6,  3,  8,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 6,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 2,  3,  4,  5,  8,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 6,  4,  5,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 2,  5,  7,  4,  2,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 2,  5,  7,  4,  2,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [20,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1

In [25]:
y_train.shape

(3594, 41)

In [26]:
y_train[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [27]:
words_input = tf.keras.layers.Input(shape=(xmax_2, ),dtype='int32', name='modelInput')
words_input

<tf.Tensor 'modelInput:0' shape=(None, 19) dtype=int32>

In [28]:
words = tf.keras.layers.Embedding(input_dim=input_dim, output_dim=128, mask_zero=True)(words_input)
words

<tf.Tensor 'embedding/Identity:0' shape=(None, 19, 128) dtype=float32>

In [42]:
tlstm = tf.keras.layers.LSTM(ymax+1, return_sequences=False)(words)
tlstm

<tf.Tensor 'lstm_1/Identity:0' shape=(None, 41) dtype=float32>

In [30]:
# ff = tf.keras.layers.Flatten()(words)

In [31]:
denseLayer = tf.keras.layers.Dense(ymax+1, activation='softmax')(tlstm)

In [43]:
modelFunc = tf.keras.Model(inputs=words_input, outputs=tlstm)

In [44]:
modelFunc.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
modelFunc.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
modelInput (InputLayer)      [(None, 19)]              0         
_________________________________________________________________
embedding (Embedding)        (None, 19, 128)           16896     
_________________________________________________________________
lstm_1 (LSTM)                (None, 41)                27880     
Total params: 44,776
Trainable params: 44,776
Non-trainable params: 0
_________________________________________________________________


In [45]:
import os
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"

In [46]:
modelFunc.fit(x_train, y_train, batch_size=128, epochs=30)

Train on 3594 samples
Epoch 1/30
 128/3594 [>.............................] - ETA: 1:17

CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Adam/Adam/update/AssignSubVariableOp/_47}}]]
	 [[Reshape_10/_44]] [Op:__inference_distributed_function_20642]

Function call stack:
distributed_function


In [36]:
modelFunc.evaluate(x_test, y_test,verbose=0)

UnknownError:  [_Derived_]  Fail to find the dnn implementation.
	 [[{{node cond/then/_0/CudnnRNNV3}}]]
	 [[model/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_10396]

Function call stack:
distributed_function -> distributed_function -> distributed_function


In [37]:
x_test[0]

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
predictions=modelFunc.predict(x_test)

UnknownError:  [_Derived_]  Fail to find the dnn implementation.
	 [[{{node cond/then/_0/CudnnRNNV3}}]]
	 [[model/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_12482]

Function call stack:
distributed_function -> distributed_function -> distributed_function


In [39]:
for i in range(len(x_test)):
    
    if np.argmax(y_test[i]) != np.argmax(predictions[i]):
        print(x_test_real[i])
        print('실제값: {} 예측값: {}'.format(np.argmax(y_test[i]), np.argmax(predictions[i])))


NameError: name 'predictions' is not defined

In [40]:
inx=2111

In [41]:

print('예측값: {} 실제값: {}'.format(np.argmax(y_test[inx]), np.argmax(predictions[inx])))

IndexError: index 2111 is out of bounds for axis 0 with size 1541